### ISSUE TITLE
Define output package location

### ISSUE THREAD

**Issue by andrzejpolis-dna** [arlac77/npm-pkgbuild#1019]
I don't see an option to define output path for package file. It is created in temporary folder and I can obtain it from output with `--verbose`. This gives me smth like:
```
dpkg-deb: building package 'foo' in '/tmp/debianRx4vS2/foo_1.0.0_all.deb'.
```

It's not very useful though for any kind of build automation. I would have to parse output.

**Comment by arlac77** [comment]
You can use the ‚—publish <directory or url>‘ option
